nachoapps/rpad-cogs-utils

- pad_api_data/pad_etl/common/dungeon_types.py
- pad_api_data/pad_etl/common/pad_util.py
- pad_api_data/pad_etl/data/dungeon.py
EDIT : Delete this. My bad, it's been a while since I used pull requests and forgot to merge my branch to master.
> Add Dungeon Types and Dungeon Comments from previous unknown values

- pad_api_data/pad_etl/processor/skill_info.py
Added comment on hp_nuke_convert & unlock_board_path type convert
eg. Mamoru and Toragon
> Added comments

- pad_api_data/pad_etl/processor/skill_info.py
eg. Baseball Haku
Fixed typing/att weren't showing
> Bug fix for dual_threshold_statrs_convert

- pad_api_data/pad_etl/processor/skill_info.py
changed 'middle row' to '3rd row from bottom'
> fixed text on row_change_convert

- pad_api_data/pad_etl/processor/skill_info.py
Also removed 'all' from enhance orb text
eg. "Enhance all Wood orbs" changed to "Enhance Wood orbs"
>  Fixed the bug where burst active mention Heal as attribute 

- pad_api_data/pad_etl/processor/skill_info.py
lock_convert correctly says "Lock all orbs" only when it locks all 10 types of orbs
> Fixed issue wher lock_convert said Lock all orbs when only given 6 orb types

- pad_api_data/pad_etl/processor/skill_info.py
also a fix to ^search due to inconsistent wording
> Updated double_orb_convert for text consistency

- pad_api_data/pad_etl/processor/skill_info.py
Fixed the issue with rainbow leader skill displaying wrong maximum activation attributes
> Fixed minor bug

- pad_api_data/pad_etl/processor/skill_info.py
Fixed calculation on max multiplier calculation according to the added parameter
>  Fixed issue with multiplier was calculated incorrectly 

- pad_api_data/pad_etl/processor/skill_info.py
Corrected the default max_attribute when none is given (changed from min_attribute to size of attribute list)
Minor skill text edit
> Fixed error in attribute_match with maximum_multilpier

- pad_api_data/pad_etl/processor/skill_info.py
Case 1: max_attr = 0, bonus_atk_mult > 0 eg. 3265 RaDra
(Scaling multi)
Case 2: bonus_atk_mult = 0 eg. 1264 Karin
(No scaling, min_attr < len(attr))
Case 3: max_attr < min_attr eg. 5004 Saber
(Scaling multi with different parameter)
Case 4: special case max_attr + minx_attr = len(attr) eg. 3930 Ideal
(Similar situation with Saber)
Case 5: The rest
>  Added cases to check for attribute_match 

- pad_api_data/pad_etl/processor/skill_info.py
Updated for new skill type
Currently only for Athena Another - 2568
active spawns certain orb on specified locations
> Updated skill type 176

- pad_api_data/pad_etl/processor/skill_info.py
Removed "all" from "Enhance all all orbs" and "Lock all all orbs"
> Updated lock_convert and enhance_convert

- pad_api_data/pad_etl/processor/skill_info.py
fixed_pos_convert now accepted squares, Ls and borders
> Updated fixed_pos_convert

- pad_api_data/pad_etl/processor/skill_info.py
Made a case where it only allows certain color to skyfall
> Updated change_skyfall_convert

- pad_api_data/pad_etl/processor/skill_info.py
Removed hard coded [Fixed 4 second movetime]
> Updated passive_stats_convert

- pad_api_data/pad_etl/processor/skill_info.py
Fixed missing text for spawn_orb_convert
fixed_pos_convert can detect multiple shapes
Added new leader skill converts(+combo ones)
> Fixed spawn_orb fixed_pos/Added new converts

- pad_api_data/pad_etl/processor/skill_info.py
L-match convert for leader skills
> Added new skill convert

- pad_api_data/pad_etl/processor/skill_info.py
fixes active skills of 5246, 5247, 5262, and 5271
also has text fix for Mowa LS where there's a double ;
> card skill type 195 suicide without nuke

- pad_api_data/pad_etl/processor/skill_info.py
Fixes zela kitty 0x ATK text
Add "and" for attributes list in the new multiple mass match LS type
Add "or" for attributes list in old single mass match LS type
Add "or" for attributes list in L shape type
> text fixes for multi color blob ls

- pad_api_data/pad_etl/processor/skill_info.py
> Fixing Alexandria Meat LS

- azure_scrape/image_download.py
Wiki relocated all seasonals to gallery page which has a slightly different tab layout. Changed scraper to support
> Modified azur scraper to support new wiki layout
